{{- $attendeeName := .Values.attendeeName | trim -}}
{{- if $attendeeName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osk-demo.fullname" . }}-config
  labels:
    {{- include "osk-demo.labels" . | nindent 4 }}
data:
  config.json: |
    {"attendeeName":"{{ $attendeeName }}"}
{{- end }}
