image:
  repository: quay.io/euthymos/workshop-greeter
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

attendeeName: ""

exposure:
  type: ingress

ingress:
  enabled: true
  ingressClassName: nginx
  host: greeter.local
