apiVersion: v1
kind: Namespace
metadata:
  name: workshop-06-cicd
  labels:
    workshop: "06"
    component: cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: workshop-06
  labels:
    workshop: "06"
    component: app
    argocd.argoproj.io/managed-by: openshift-gitops
