image:
  repository: ddsnexus01a.minv.sk:500X/repository/docker-devops/osk-demo:latest-ppc64le
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

attendeeName: ""
