FROM registry.access.redhat.com/ubi9/nodejs-20 as builder

WORKDIR /opt/app-root/src

USER root

COPY ./package.json .

RUN npm install

COPY . .

RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-126

USER root

COPY --from=builder --chown=1001:0 /opt/app-root/src/dist /opt/app-root/src

USER 1001
EXPOSE 8080

CMD nginx -g "daemon off;"